# 使用官方 Node.js 作为基础镜像
FROM node:16 AS build

# 设置工作目录
WORKDIR /app

# 复制 package.json 和 package-lock.json 文件
COPY package*.json ./

# 安装项目依赖
RUN npm install

# 复制其余的项目文件
COPY . .

# 构建项目
RUN npm run build

# 使用 Nginx 作为生产环境的 web 服务器
FROM nginx:alpine

# 复制构建结果到 Nginx 服务器的默认静态文件目录
COPY --from=build /app/dist /usr/share/nginx/html

# 暴露 Nginx 的 80 端口
EXPOSE 80

# 启动 Nginx
CMD ["nginx", "-g", "daemon off;"]
